name: docker
on:
  push:
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    steps:
      - name: check docker version
        run: |
          docker version
