name: needs
on:
  push:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo a

  b:
    runs-on: ubuntu-latest
    steps:
      - run: echo b

  c:
    needs: [a, b]
    runs-on: ubuntu-latest
    steps:
      - run: echo a
